### ISSUE TITLE
Have support for checkpointing the upstream master

### ISSUE THREAD

**Issue by pvam** [vrajat/git-patch#7]
Currently we begin the patching by downloading latest commit from master. Then we manually resolve conflicts in an iterative fashion. In each iteration we expect to resume from the patch we manually fixed last time. This desired behaviour degrades when master has an update at the later point of time and is in conflict with one of the earlier patches. This can repeatedly break in-progress patch work making user go back and forth. 

**Hack:**
To make this more productive, we can have a pre-processing step wherein you cut the upstream master branch at a certain commit and have that serve as a master for the next steps. With this change, we will only move forward while fixing patches and things remain more clear. The downside of-course is that we miss the commits introduced after the cut.

**Comment by vrajat** [comment]
Do you need a branch or a commit id is sufficient ?

**Comment by vrajat** [comment]
Its possible to rebase to a commit id as well. Relevant commands for all possible options are available in http://stackoverflow.com/questions/7744049/git-how-to-rebase-to-a-specific-commit

**Comment by vrajat** [comment]
A simpler option maybe to provide an option to skip fetch of upstream.
